### ISSUE TITLE
assert.deepEqual throws TypeError when comparing Symbols

### ISSUE THREAD

**Issue by HarrySarson** [jquery/qunit#1056]
When a comparison between arrays containing Symbols fails, rather than printing an error message the `assert.deepEqual` function throws a type error.
```
  QUnit.test('`a test`', assert => {
    assert.expect(1);

    assert.deepEqual([Symbol('mySymbol')], [5]);
  });
```

Results in the following output

``` bash
 FAIL - `a test`
C:\Users\Harry\WebstormProjects\IteratorUtil\node_modules\qunit-extras\qunit-extras.js:471
            'Actual: ' + String(entry.actual)
                         ^

TypeError: Cannot convert a Symbol value to a string
    at Array.toString (native)
    at Array.<anonymous> (C:\Users\Harry\WebstormProjects\IteratorUtil\node_modules\qunit-extras\qunit-extras.js:471:26)
    at runLoggingCallbacks (C:\Users\Harry\WebstormProjects\IteratorUtil\node_modules\qunit-extras\node_modules\qunitjs\qunit\qunit.js:291:17)
    at Object.Test.finish (C:\Users\Harry\WebstormProjects\IteratorUtil\node_modules\qunit-extras\node_modules\qunitjs\qunit\qunit.js:822:3)
    at Object.<anonymous> (C:\Users\Harry\WebstormProjects\IteratorUtil\node_modules\qunit-extras\qunit-extras.js:340:18)
    at Object.<anonymous> (C:\Users\Harry\WebstormProjects\IteratorUtil\node_modules\qunit-extras\qunit-extras.js:219:22)
    at Object.<anonymous> (C:\Users\Harry\WebstormProjects\IteratorUtil\node_modules\qunit-extras\qunit-extras.js:412:16)
    at Object.finish (C:\Users\Harry\WebstormProjects\IteratorUtil\node_modules\qunit-extras\qunit-extras.js:219:22)
    at C:\Users\Harry\WebstormProjects\IteratorUtil\node_modules\qunit-extras\node_modules\qunitjs\qunit\qunit.js:885:11
    at process (C:\Users\Harry\WebstormProjects\IteratorUtil\node_modules\qunit-extras\node_modules\qunitjs\qunit\qunit.js:550:24)
```

This is because string concatenation with `Symbols` fails: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toString#No_string_concatenation

I believe that somewhere `[Symbol('mySymbol')].toString()` is called which throws the error.

**Comment by trentmwillis** [comment]
@HarrySarson can you provide a failing test as either a PR or in a JSBin? Based on the stack trace above, it seems like this issue is actually in the qunit-extras plugin you seem to be using, so I'd like to verify if there is any behavior actually broken on our side.

**Comment by HarrySarson** [comment]
@trentmwillis ah it could well be a problem with qunit-extras, can I check tomorrow and get back to you.

**Comment by HarrySarson** [comment]
@trentmwillis Yes you are right, its and issue with qunit-extras.
